// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: activityLog.sql

package sqlc

import (
	"context"
)

const createActivity = `-- name: CreateActivity :one
insert into activity_log(user_id, amount)
values($1, $2)
RETURNING id, user_id, amount, created_at
`

type CreateActivityParams struct {
	UserID int32
	Amount string
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (ActivityLog, error) {
	row := q.db.QueryRowContext(ctx, createActivity, arg.UserID, arg.Amount)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
