// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"time"
)

type Account struct {
	ID int32
	// 帳號
	Name string
	// 密碼
	Password  string
	Balance   string
	Currency  string
	CreatedAt time.Time
}

type Entry struct {
	ID        int32
	AccountID int32
	// postive or negative
	Amount    string
	CreatedAt time.Time
}

type Transfer struct {
	ID            int32
	FromAccountID int32
	ToAccountID   int32
	// just postive
	Amount    string
	CreatedAt time.Time
}
