// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"
)

type Querier interface {
	AddBalance(ctx context.Context, arg AddBalanceParams) (Balance, error)
	CreateActivity(ctx context.Context, arg CreateActivityParams) (ActivityLog, error)
	CreateBalance(ctx context.Context, arg CreateBalanceParams) (Balance, error)
	CreateTransferLog(ctx context.Context, arg CreateTransferLogParams) (TransferLog, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetActivity(ctx context.Context, userID int32) ([]ActivityLog, error)
	GetBalanceByUser(ctx context.Context, userID int32) ([]Balance, error)
	GetSpecifyCurrencyBalanceByUser(ctx context.Context, arg GetSpecifyCurrencyBalanceByUserParams) (Balance, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByName(ctx context.Context, name string) (User, error)
	InserOrUpdateBalance(ctx context.Context, arg InserOrUpdateBalanceParams) (Balance, error)
	SubBalance(ctx context.Context, arg SubBalanceParams) (Balance, error)
}

var _ Querier = (*Queries)(nil)
