// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: transferLog.sql

package sqlc

import (
	"context"
)

const createTransferLog = `-- name: CreateTransferLog :one
insert into transfer_log(from_user_id, to_user_id, amount)
values($1, $2, $3)
RETURNING id, from_user_id, to_user_id, amount, created_at
`

type CreateTransferLogParams struct {
	FromUserID int32
	ToUserID   int32
	Amount     string
}

func (q *Queries) CreateTransferLog(ctx context.Context, arg CreateTransferLogParams) (TransferLog, error) {
	row := q.db.QueryRowContext(ctx, createTransferLog, arg.FromUserID, arg.ToUserID, arg.Amount)
	var i TransferLog
	err := row.Scan(
		&i.ID,
		&i.FromUserID,
		&i.ToUserID,
		&i.Amount,
		&i.CreatedAt,
	)
	return i, err
}
